# Generated by Django 3.2.8 on 2022-08-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todonote_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todonote',
            old_name='project_name',
            new_name='project',
        ),
    ]
